### ISSUE TITLE
 Quantifying labelling efficiency for Priming run

### ISSUE THREAD

**Issue by SGhosh2019** [qingyuhms/TomahtoProgram#1]
Hi 

I have a set of reference peptides which I labelled with TMT0 for priming run and planning  to use TOMAHAQ companion. Can I use same experimental setup for Tomahto also? I ran both the labelled and unlabelled samples with the Priming run method (separate inclusion list for labelled and unlabelled) in Fusion and wanted to evaluate the labelling efficiency, just to make sure that I properly labelled the trigger peptides before spike them in real sample! How do I proceed?

Best regards,
Sudip

**Comment by qingyuhms** [comment]
I am not sure what your question is so I will just try answer based on what I understand. First of all Tomahto does not check labeling efficiency and it has to be done before you spike them in. Secondly why would you run labeled and unlabeled separately? If your goal is to evaluate labeling efficiency, I'd suggest running the labeled sample and search the data with TMT set to variable modification. Just count the labeled/unlabeled PSMs you get your result.
